services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    depends_on:
      - db

  frontend:
    container_name: next_frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  backend:

volumes:
  db-vol:
